export async function onRequest(context) {
  const { request, env, params } = context;
  const id = params.id;

  // 1. Fetch the default index.html asset
  let html = "";
  try {
    const url = new URL(request.url);
    url.pathname = "/index.html";
    const assetResponse = await env.ASSETS.fetch(url);
    if (assetResponse.ok) {
      html = await assetResponse.text();
    } else {
      return new Response("Index asset not found", { status: 404 });
    }
  } catch (err) {
    return new Response("Error loading index.html: " + err.message, { status: 500 });
  }

  // 2. Initialize default meta values
  let titre = "EbookStore - Les Meilleurs Ebooks de Développement";
  let description = "Découvrez des ebooks de haute qualité pour propulser votre carrière de développeur en Afrique.";
  let url_couverture = "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400";

  // 3. Try to fetch ebook data from Supabase REST API
  const supabaseUrl = env.VITE_SUPABASE_URL;
  const supabaseAnonKey = env.VITE_SUPABASE_ANON_KEY;

  if (id && supabaseUrl && supabaseAnonKey) {
    try {
      const dbUrl = `${supabaseUrl}/rest/v1/ebooks?id=eq.${id}&select=titre,description,url_couverture`;
      const dbResponse = await fetch(dbUrl, {
        method: "GET",
        headers: {
          "apikey": supabaseAnonKey,
          "Authorization": `Bearer ${supabaseAnonKey}`,
          "Content-Type": "application/json",
        }
      });

      if (dbResponse.ok) {
        const ebooks = await dbResponse.json();
        if (ebooks && ebooks.length > 0) {
          const ebook = ebooks[0];
          if (ebook.titre) titre = ebook.titre;
          if (ebook.description) {
            let desc = ebook.description;
            if (desc.length > 150) {
              desc = desc.substring(0, 147) + "...";
            }
            description = desc;
          }
          if (ebook.url_couverture) url_couverture = ebook.url_couverture;
        }
      }
    } catch (err) {
      console.error("Failed to fetch ebook metadata from Supabase:", err);
    }
  }

  // Helper to escape HTML attributes safely
  function escapeHtml(str) {
    if (!str) return "";
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  const escapedTitle = escapeHtml(titre);
  const escapedDesc = escapeHtml(description);
  const escapedImage = escapeHtml(url_couverture);

  // 4. Inject dynamic Open Graph meta tags into the head
  const ogTags = `
  <!-- Dynamic Open Graph Preview Generated by Cloudflare Pages Function -->
  <meta property="og:title" content="${escapedTitle}">
  <meta property="og:description" content="${escapedDesc}">
  <meta property="og:image" content="${escapedImage}">
  <meta property="og:url" content="https://ebookstore-73b.pages.dev/ebook/${id}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="${escapedTitle}">
  <meta name="twitter:description" content="${escapedDesc}">
  <meta name="twitter:image" content="${escapedImage}">
  `;

  // Inject before the closing </head> tag
  if (html.includes("</head>")) {
    html = html.replace("</head>", `${ogTags}\n</head>`);
  } else {
    // Fallback if no head closing tag is found
    html = html + ogTags;
  }

  return new Response(html, {
    headers: {
      "Content-Type": "text/html;charset=UTF-8",
      "Cache-Control": "public, max-age=300", // Cache for 5 mins to optimize performance
    }
  });
}
