export async function onRequest(context) {
  const { request, env, params } = context;
  const slug = params.slug;

  // 1. Fetch the default app.html asset
  let html = "";
  try {
    const url = new URL(request.url);
    url.pathname = "/app.html";
    const assetResponse = await env.ASSETS.fetch(url);
    if (assetResponse.ok) {
      html = await assetResponse.text();
    } else {
      return new Response("Index asset not found", { status: 404 });
    }
  } catch (err) {
    return new Response("Error loading index.html: " + err.message, { status: 500 });
  }

  // 2. Initialize default meta values
  let titre = "Offre d'Emploi - EbookStore Recrutement";
  let description = "Découvrez des opportunités de carrière uniques sur la plateforme EbookStore Recrutement en Afrique.";
  let entreprise = "Recruteur";
  let lieu = "Afrique";
  let type_contrat = "CDI";
  let hasData = false;

  // 3. Fetch specific job offer data from Supabase REST API
  const supabaseUrl = env.VITE_SUPABASE_URL || env.SUPABASE_URL;
  const supabaseAnonKey = env.VITE_SUPABASE_ANON_KEY || env.SUPABASE_ANON_KEY;

  if (slug && supabaseUrl && supabaseAnonKey) {
    try {
      const dbUrl = `${supabaseUrl}/rest/v1/job_offers?slug=eq.${slug}&select=titre,description,entreprise,lieu,type_contrat,salaire_min,salaire_max,devise,secteur`;
      const dbResponse = await fetch(dbUrl, {
        method: "GET",
        headers: {
          "apikey": supabaseAnonKey,
          "Authorization": `Bearer ${supabaseAnonKey}`,
          "Content-Type": "application/json",
        }
      });

      if (dbResponse.ok) {
        const offers = await dbResponse.json();
        if (offers && offers.length > 0) {
          const offer = offers[0];
          if (offer.titre) titre = offer.titre;
          if (offer.description) description = offer.description;
          if (offer.entreprise) entreprise = offer.entreprise;
          if (offer.lieu) lieu = offer.lieu;
          if (offer.type_contrat) type_contrat = offer.type_contrat;
          hasData = true;
        }
      }
    } catch (err) {
      console.error("Failed to fetch job metadata from Supabase:", err);
    }
  }

  // Helper to escape HTML safely
  function escapeHtml(str) {
    if (!str) return "";
    return str
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");
  }

  const escapedTitle = escapeHtml(titre);
  const escapedCompany = escapeHtml(entreprise);
  const escapedLieu = escapeHtml(lieu);
  const escapedContract = escapeHtml(type_contrat);
  
  // Truncate description for meta tag
  let truncatedDesc = description;
  if (truncatedDesc.length > 160) {
    truncatedDesc = truncatedDesc.substring(0, 157) + "...";
  }
  const escapedMetaDesc = escapeHtml(truncatedDesc);

  // 4. Construct Structured Data (JSON-LD) for JobPosting
  const jobPostingSchema = {
    "@context": "https://schema.org",
    "@type": "JobPosting",
    "title": titre,
    "description": description,
    "datePosted": "2026-07-11", // Fallback date
    "validThrough": "2027-07-11",
    "employmentType": type_contrat,
    "hiringOrganization": {
      "@type": "Organization",
      "name": entreprise,
      "sameAs": "https://ebookstore-73b.pages.dev/"
    },
    "jobLocation": {
      "@type": "Place",
      "address": {
        "@type": "PostalAddress",
        "addressLocality": lieu,
        "addressCountry": "Afrique"
      }
    }
  };

  const jsonLdString = JSON.stringify(jobPostingSchema, null, 2);

  // 5. Construct semantic content (SSR partial HTML)
  const partialSsrHtml = `
  <!-- Partial SSR Content for Robots and AI crawlers (Visually Hidden) -->
  <div class="sr-only" aria-hidden="true" style="position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0, 0, 0, 0); white-space: nowrap; border: 0;">
    <h1>${escapedTitle} chez ${escapedCompany}</h1>
    <p><strong>Lieu :</strong> ${escapedLieu}</p>
    <p><strong>Contrat :</strong> ${escapedContract}</p>
    
    <h2>Description du poste</h2>
    <p>${escapeHtml(description)}</p>
    
    <p>
      Intéressé par cette offre d'emploi ? Vous pouvez postuler directement en allant sur :
      <a href="https://ebookstore-73b.pages.dev/job/${slug}">Postuler à ${escapedTitle}</a>
    </p>
  </div>
  `;

  // 6. Set up Dynamic Meta Tags (Open Graph, Twitter, Description, Canonical)
  const ogTags = `
  <!-- Dynamic Meta Tags Generated by Cloudflare Pages Function -->
  <link rel="canonical" href="https://ebookstore-73b.pages.dev/job/${slug}" />
  <meta name="description" content="${escapedMetaDesc}" />
  <meta property="og:title" content="${escapedTitle} | ${escapedCompany} | EbookStore Recrutement">
  <meta property="og:description" content="${escapedMetaDesc}">
  <meta property="og:url" content="https://ebookstore-73b.pages.dev/job/${slug}">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="${escapedTitle} | ${escapedCompany} | EbookStore Recrutement">
  <meta name="twitter:description" content="${escapedMetaDesc}">
  <script type="application/ld+json">
${jsonLdString}
  </script>
  `;

  // Replace default title tag
  if (html.includes("<title>")) {
    html = html.replace(/<title>.*?<\/title>/, `<title>${escapedTitle} | ${escapedCompany} | EbookStore Recrutement</title>`);
  }

  // Inject meta tags and structured data into <head>
  if (html.includes("</head>")) {
    html = html.replace("</head>", `${ogTags}\n</head>`);
  } else {
    html += ogTags;
  }

  // Inject semantic text block into the <body>
  if (html.includes("<body>")) {
    html = html.replace("<body>", `<body>\n${partialSsrHtml}`);
  } else if (html.includes("<body ")) {
    html = html.replace(/<body[^>]*>/, (match) => `${match}\n${partialSsrHtml}`);
  } else {
    html += partialSsrHtml;
  }

  return new Response(html, {
    headers: {
      "Content-Type": "text/html;charset=UTF-8",
      "Cache-Control": "public, max-age=600", // Cache for 10 mins
    }
  });
}
